spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3308/vehicledb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:ibemgibemg1!}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=${JWT_SECRET:404e635266556a586e3272357538782f413f4428472b4b6250645367566b5970}
jwt.expiration-ms=86400000

server.port=${PORT:8080}
server.address=0.0.0.0
